FROM python:3.11-slim

WORKDIR /app

# Dépendances système nécessaires
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    g++ \
    libsnappy-dev \
    libzstd-dev \
    liblz4-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*


COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 9000

CMD ["uvicorn", "Src.main:app", "--host", "0.0.0.0", "--port", "9000"]
